language: node_js
node_js:
 - "10"
 - "12"
 - "node"
script:
  - npm run build
  - npm run lint
  - npm test
  - npm run spec
after_success:
  - npm run coveralls
cache:
  - npm
  - directories:
    - .rdf-test-suite-cache
